import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Separator } from "@/components/ui/separator";

export const metadata = {
  title: "Methodology — Constituency Pulse",
};

export default function MethodologyPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-8 px-4 py-10">
      <div className="space-y-2">
        <h1 className="text-2xl font-semibold tracking-tight">Methodology &amp; scope</h1>
        <p className="text-muted-foreground">
          This page explains what this prototype does, what it deliberately excludes, and where
          each number comes from. It&rsquo;s adapted from the platform&rsquo;s own product requirements.
        </p>
      </div>

      <Alert>
        <AlertTitle>Every account, post, and analysis on this site is synthetic demo data</AlertTitle>
        <AlertDescription>
          Everything social-platform-related here — accounts, handles, posts, follower counts,
          engagement numbers, growth history, sentiment/topic/narrative labels, the influence
          graph, and cross-platform amplification links — is entirely fictional, generated by
          deterministic code in this repo (see <code>src/data/mock/</code>). None of it comes from
          a real platform API, a real LLM call, or a database; there isn&rsquo;t one wired up. An
          earlier version of this prototype tracked real, named YouTube channels and ran a real
          Anthropic model over real RSS content; both were removed in favor of a fully synthetic
          dataset, since attaching computed sentiment/narrative scores to real named creators —
          even genuinely computed rather than fabricated — was judged too close to the
          defamation/reputational risk this platform&rsquo;s own source PRD (Section 7) warns
          against, for a link meant to be shared around. Making the whole layer synthetic removes
          that risk at the source rather than mitigating it after the fact. The election results
          and Digital Engagement Index figures described below are the exception: those remain
          real, cited, offline data.
        </AlertDescription>
      </Alert>

      <section className="space-y-3">
        <h2 className="text-lg font-medium">What this is</h2>
        <p className="text-sm text-muted-foreground">
          A constituency-level read on which issues and narratives are gaining traction on
          social/new media, and which named public accounts are driving that traction —
          prioritized toward electorally competitive (swing) constituencies with high social-media
          penetration. It is political and media intelligence infrastructure, not a generic civic
          dashboard; the swing-constituency and named-account targeting are inherently
          electoral-strategy concepts and this page does not obscure that.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-medium">Scope</h2>
        <div className="grid gap-3 sm:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle className="text-sm">In scope</CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-1">
              <p>Fictional creator/account personas (not real people) standing in for the
                named-public-account layer, spanning YouTube, X, Instagram, and Facebook</p>
              <p>Aggregated, constituency-level sentiment over that fictional content</p>
              <p>Synthetic engagement metrics (likes, comment counts, shares) as aggregate numbers
                — never individual-level</p>
              <p>Real historical election results and a real digital-engagement proxy, both
                offline and cited (see below)</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="text-sm">Explicitly out of scope</CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-1">
              <p>Private individual profiles, closed groups, DMs</p>
              <p>Individual commenter names, profile links, or identifiers</p>
              <p>Cross-referencing against voter rolls or any other PII dataset</p>
              <p>De-anonymizing pseudonymous accounts</p>
              <p>Booth-level or individual-level mapping, voter scoring</p>
              <p>Platform scraping that violates a platform&rsquo;s Terms of Service</p>
            </CardContent>
          </Card>
        </div>
      </section>

      <Separator />

      <section className="space-y-3">
        <h2 className="text-lg font-medium">Where the data comes from</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm text-muted-foreground">
          <li>
            <strong>Election results &amp; swing-tier classification:</strong> real historical Lok
            Sabha results across multiple cycles for a curated subset of constituencies. Margin
            volatility, vote-share flip frequency, and closeness index are computed from those real
            results — see each constituency&rsquo;s detail page for its specific source citations.
          </li>
          <li>
            <strong>Digital Engagement Index:</strong> a documented per-state proxy derived from
            public telecom/internet-penetration data, cited per constituency.
          </li>
          <li>
            <strong>Tracked accounts:</strong> fictional Indian-context creator/publisher personas
            (invented names, handles, bios, and platform — see /channels and
            <code>src/data/mock/accounts.ts</code>), spanning the same politically-diverse,
            multi-region spread the original real-account design aimed for.
          </li>
          <li>
            <strong>Posts, engagement, and growth history:</strong> generated by deterministic
            code (<code>src/data/mock/posts.ts</code>, <code>growth-history.ts</code>) seeded off
            each account&rsquo;s id, so the same account always produces the same posts, follower
            trajectory, and engagement numbers on every load — nothing here is drawn from a live
            platform or randomized per request.
          </li>
          <li>
            <strong>Sentiment, topics, and narrative summaries:</strong> produced by a
            deterministic, rule-based function (<code>src/data/mock/mock-analysis.ts</code>) that
            keyword-matches each fabricated post&rsquo;s text and maps that to a topic list, a
            sentiment score, and a templated summary sentence. This is not a language model call
            of any kind — no prompt is sent anywhere, and the same post always scores the same way.
          </li>
          <li>
            <strong>Influence graph &amp; cross-platform amplification:</strong> the connections
            and amplification weights shown on /network are likewise generated data
            (<code>src/data/mock/amplification.ts</code>), illustrating what a real
            cross-platform-linkage analysis would look like without asserting that any of the
            underlying accounts or reposting behavior is real.
          </li>
        </ul>
      </section>

      <Separator />

      <section className="space-y-3">
        <h2 className="text-lg font-medium">Compliance notes</h2>
        <p className="text-sm text-muted-foreground">
          A production deployment of a platform like this carries real obligations this prototype
          does not resolve on its own: platform Terms of Service for any automated data collection;
          India&rsquo;s DPDP Act 2023 wherever personal data is processed, even from public posts; the
          Election Commission of India&rsquo;s Model Code of Conduct and political advertising/data-use
          rules if used by or for a party, candidate, or campaign vendor; and defamation risk in how
          sentiment about named commentators is stored, scored, and shared. This prototype sidesteps
          the sharpest of those risks by construction rather than by process controls: there are no
          real platform accounts, real posts, or real people anywhere in the social-media layer for
          any of those obligations to attach to, and the neutral, non-accusatory framing rules are
          carried through even into synthetic content. None of that is a substitute for a real
          legal/compliance review — it only means a real deployment would be starting that review
          from real data for the first time, not carrying this prototype&rsquo;s risk forward into it.
        </p>
      </section>
    </div>
  );
}
